language: node_js

# https://github.com/nodejs/Release
# Specify current LTS version here, which is used for publishing to npm
node_js:
  - 10 # EOL: April 2021

os:
  - linux

# https://github.com/nodejs/Release
matrix:
  fast_finish: true
  include:
    - name: "Windows build"
      os: windows
      cache: false # windows cache uploads are slow
      env: YARN_GPG=no # starts gpg-agent that never exits

    - name: "macOS build"
      os: osx

    # Next node version
    - node_js: 11 # EOL: June 2019

services:
  - xvfb

cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update && sudo apt-get install -q libxss-dev; fi

script:
  - npm install -g nyc
  - npx nyc mocha

notifications:
  email:
    on_success: never
    on_failure: change

after_success:
  - bash <(curl -s https://codecov.io/bash)

script:
  - npm run dev
